run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - misspell
    - unconvert
    - unparam
  disable:
    - goimports

issues:
  exclude-dirs:
    - data
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

linters-settings:
  goimports:
    local-prefixes: github.com/vladislavdragonenkov/news-telegram-bot
